version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: minerva_backend
    ports:
      - "8003:8003"
    volumes: 
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=minerva_user 
      - DB_PASSWORD=minerva_pass
      - OLLAMA_URL= http://ollama:11434
    depends_on:
      - database #il backend aspetta che il db sia pronto
      - ollama #il backend aspetta che ollama sia pronto
        

  frontend:
    build: ./frontend 
    container_name: minerva_frontend
    ports:
      - "8004:8004"
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_URL=http://backend:8003
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - backend
  
  database: 
    image: mariadb:10.11
    container_name: minerva_db 
    ports: 
      - "3306:3306"
    environment: 
      - MARIADB_ROOT_PASSWORD=rootpass 
      - MARIADB_DATABASE=minerva_db 
      - MARIADB_USER=minerva_user 
      - MARIADB_PASSWORD=minerva_pass 
    volumes: 
      - ./mariadb_data:/var/lib/mysql
  ollama:
    image: ollama/ollama:latest
    container_name: minerva_ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama serve & sleep 5 && ollama pull llama3.2:3b && wait"]
