version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: minerva_backend
    ports:
      - "8003:8003"
    volumes: 
      - ./:/app
        

  frontend:
    build:
      context: ./frontend
    ports:
      - "8004:8004"
    environment:
      - BACKEND_URL=http://backend:8003
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - backend
    volumes: 
      - ./:/app
  ollama:
    image: ollama/ollama:latest
    container_name: minerva_ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama serve & sleep 5 && ollama pull llama3.2:3b && wait"]